server.port=8080
logging.file.name=logs/tdjmap.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
spring.application.name=TDJMap
spring.datasource.url=jdbc:postgresql://127.0.0.1:15432/tandanji
spring.datasource.username=tandanji
spring.datasource.password=tandanji
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=tandanji

fatsecret.client-id=339f8fee1d9644ad88ebc972f2c90bfa
fatsecret.client-secret=c1e9da9c776f4786a69656d1b8886fd1

jwt.secret=idGrysSetZ6kHa2YqV1BoEQfWUPNgDF8LM45RzuwXhAJKpmOITcl0Cbnv37x9j
jwt.access-token-expiry=3600000
jwt.refresh-token-expiry=2592000000
kakao.client-id=c50cf4ef68cf202f940675304e48383e
kakao.token-url=https://kauth.kakao.com/oauth/token
kakao.user-info-url=https://kapi.kakao.com/v2/user/me
kakao.redirect-uri=http://localhost:5173/oauth/callback

app.upload.dir=uploads/
app.image.base-url=http://localhost:8080/images/

# tandanji.ai.base-url=http://192.168.110.63:3221
tandanji.ai.base-url=https://allfor-tandanji-ai.rbwise.work
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=30MB

