jwt.access-token-expiry=3600000
jwt.refresh-token-expiry=2592000000

kakao.token-url=https://kauth.kakao.com/oauth/token
kakao.user-info-url=https://kapi.kakao.com/v2/user/me

app.upload.dir=uploads/
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=30MB

spring.config.import=optional:file:.env[.properties]
